Proyecto_JYJSAS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
# Importa el archivo views de inventarios para redireccionar con el
# path("", views.index, name="index") a la url http://127.0.0.1:8000
from inventarios import views


urlpatterns = [
    path('admin/', admin.site.urls),
    # Path para la aplicacion inventarios
    path('inventarios/', include('inventarios.urls')),
    # Redirecciona como pagina principal a la url http://127.0.0.1:8000/
    path("", views.index, name="index"),
    # Path para la aplicacion operaciones
    path('operaciones/', include('operaciones.urls'))
]

inventarios/urls.py
from django.urls import path
from . import views


# Namespace para evitar conflicto entre urls llamadas igual pero en diferentes
# aplicaciones
app_name = "inventarios"

urlpatterns = [
    # Camino a la pagina principal de la empresa
    path("", views.index, name="index"),
    path("mision", views.mision, name="mision"),
    path("vision", views.vision, name="vision"),
    path("contacto", views.contacto, name="contacto"),
    path("enviarcorreogeneral", views.enviarcorreogeneral,
         name="enviarcorreogeneral"),
    path("ingresar", views.ingresar, name="ingresar"),
    path("salir", views.salir_view, name="salir"),
    path("gerente", views.gerente, name="gerente"),
    path("almacenista", views.almacenista, name="almacenista"),
    path("directoroperativo", views.directoroperativo,
         name="directoroperativo"),
    path("contratista", views.contratista, name="contratista"),
    path("signup", views.signup_view, name="signup")
]

operaciones/urls.py
from django.urls import path
from . import views


# Namespace para evitar conflicto entre urls llamadas igual pero en diferentes
# aplicaciones
app_name = "operaciones"

urlpatterns = [
     ############################ Paginas gerente ##############################
     path("", views.index, name="reportesinventario"),
     path("nuevomaterial", views.nuevomaterial, name="nuevomaterial"),
     path("nuevoproveedor", views.nuevoproveedor, name="nuevoproveedor"),
     path("nuevoproyecto", views.nuevoproyecto, name="nuevoproyecto"),
     path("nuevocontratista", views.nuevocontratista, name="nuevocontratista"),
     # Pagina de entradas de almacen
     path("entradaalmacen", views.entradaalmacen, name="entradaalmacen"),
     path("autsalidamaterial", views.autsalidamaterial,
          name="autsalidamaterial"),
     path("eliminarcontratista", views.eliminarcontratista,
          name="eliminarcontratista"),
     path("eliminarproducto", views.eliminarproducto, name="eliminarproducto"),
     path("eliminarproveedor", views.eliminarproveedor,
          name="eliminarproveedor"),
     path("eliminarproyecto", views.eliminarproyecto,
          name="eliminarproyecto"),
     # Pagina borrado exclusiva de un contratista
     path("borrarcontratista<int:codigo_contratista>", views.borrarcontratista,
          name="borrarcontratista"),
     # Pagina borrado exclusiva de un producto de almacen
     path("borrarproducto<int:codigo_producto>", views.borrarproducto,
          name="borrarproducto"),
     # Pagina borrado exclusiva de un proveedor
     path("borrarproveedor<int:codigo_proveedor>", views.borrarproveedor,
          name="borrarproveedor"),
     # Pagina borrado exclusiva de un proyecto
     path("borrarproyecto<int:codigo_proyecto>", views.borrarproyecto,
          name="borrarproyecto"),
     # Pagina para editar exclusivamente a un contratista
     path("editarcontratista<int:codigo_contratista>", views.editarcontratista,
          name="editarcontratista"),
     # Pagina de edicion exclusiva de un producto
     path("editarproducto<int:codigo_producto>", views.editarproducto,
          name="editarproducto"),     
     # Pagina de edicion exclusiva de un proveedor
     path("editarproveedor<int:codigo_proveedor>",
          views.editarproveedor, name="editarproveedor"),
     # Pagina de edicion exclusiva de un proyecto
     path("editarproyecto<int:codigo_proyecto>", views.editarproyecto,
          name="editarproyecto"),
     # Ruta para redirecionar al gerente al menu de el mismo
     path("redirecciongerente", views.redirecciongerente,
          name="redirecciongerente"),  # Redirecciona al menu del gerente
     
     # ######################### Paginas almacenista ########################
     path("almacenistanuevomaterial", views.almacenistanuevomaterial,
          name="almacenistanuevomaterial"),
     # Pagina que lista todos los productos del almacen
     path("almacenistalistaproductos", views.almacenistalistaproductos,
          name="almacenistalistaproductos"),
     # Pagina para editar un producto especifico de la base de datos
     path("almacenistaeditarproducto<int:codigo_producto>", views.almacenistaeditarproducto,
          name="almacenistaeditarproducto"),
     # Pagina que lista todos los proveedores
     path("almacenistalistaproveedores", views.almacenistalistaproveedores,
          name="almacenistalistaproveedores"),
     # Pagina para editar un proveedor especifico de la base de datos
     path("almacenistaeditarproveedor<int:codigo_proveedor>",
          views.almacenistaeditarproveedor, name="almacenistaeditarproveedor"),
     path("salidaalmacen", views.salidaalmacen, name="salidaalmacen"),
     path("almacenistaentrada", views.almacenistaentrada,
          name="almacenistaentrada"),
     path("solautsalida", views.solautsalida, name="solautsalida"),
     path("almacenistareporteinventarios", views.almacenistareporteinventarios,
          name="almacenistareporteinventarios"),
     path("almacenistanuevoproveedor", views.almacenistanuevoproveedor,
          name="almacenistanuevoproveedor"),
     path("redireccionalmacenista", views.redireccionalmacenista,
          name="redireccionalmacenista"),  # Redirecciona al menu almacenista

     # ##################### Paginas director operativo #######################
     path("operativoreporteinventarios", views.operativoreporteinventarios,
          name="operativoreporteinventarios"),
     path("solicitudmateriales", views.solicitudmateriales,
          name="solicitudmateriales"),
     path("operativonuevoproyecto", views.operativonuevoproyecto,
          name="operativonuevoproyecto"),
     path("operativolistaproyectos", views.operativolistaproyectos,
          name="operativolistaproyectos"),
     path("operativoeditarproyecto<int:codigo_proyecto>",
          views.operativoeditarproyecto, name="operativoeditarproyecto"),
     path("redireccionoperativo", views.redireccionoperativo,
          name="redireccionoperativo"),  # Redirecciona al menu del operativo

     # ######################## Paginas contratistas ##########################
     path("proyectoscontratista", views.proyectoscontratista,
          name="proyectoscontratista"),
     # path("proyectoscontratista<int:pk>", views.proyectoscontratista,
     #      name="proyectoscontratista"),
     path("novedades", views.novedades, name="novedades"),
     path("enviarnovedades", views.enviarnovedades, name="enviarnovedades"),
     path("redireccioncontratista", views.redireccioncontratista,
         name="redireccioncontratista"),  # Redirecciona al menu contratistas
     
     # ###################### Paginas de Reportes #############################
     path("reportedisponibilidad", views.reportedisponibilidad,
          name="reportedisponibilidad"),
     path("reportedisponibilidadalmacenista",
          views.reportedisponibilidadalmacenista,
          name="reportedisponibilidadalmacenista"),
     path("reportedisponibilidadoperativo",
          views.reportedisponibilidadoperativo,
          name="reportedisponibilidadoperativo"),
     path("reporteporproyecto", views.reporteporproyecto,
          name="reporteporproyecto"),
     path("almacenistareporteporproyecto", views.almacenistareporteporproyecto,
          name="almacenistareporteporproyecto"),
     path("operativoreporteporproyecto", views.operativoreporteporproyecto,
          name="operativoreporteporproyecto")
]

inventarios/models.py
from django.db import models

inventarios/views.py
from django.shortcuts import render, redirect
# Importa para crear el formulario de autenticacion de usuarios.
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UsernameField
# Importa para usar las funciones de log in y log out.
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
# Importa el modelo de usuarios para despues enviarlo como argumento a las
# paginas en que se requiera
from operaciones.models import CustomUser
from django.contrib.auth.decorators import login_required
# Importa el formulario para registrar un nuevo usuario
from operaciones.forms import SignUpForm
# Importa el archivo settings.py para poder enviar el correo.
from django.conf import settings
from django.core.mail import send_mail


# Create your views here.
def index(request):
    return render(request, "inventarios/index.html")


def mision(request):
    return render(request, "inventarios/mision.html")


def vision(request):
    return render(request, "inventarios/vision.html")


def contacto(request):
    return render(request, "inventarios/contacto.html")


# Funcion para enviar correos al correo registrado
def enviarcorreogeneral(request):
    if request.method == "POST":
        asunto = request.POST["txtAsunto"]
        mensaje = request.POST["txtMensaje"] + \
            " / Email: " + request.POST["txtEmail"]
        email_desde = settings.EMAIL_HOST_USER
        email_para = ["salvadorexamplemail@gmail.com"]
        send_mail(asunto, mensaje, email_desde,
                  email_para, fail_silently=False)
        return render(request, "inventarios/contacto.html", {
            "mensaje": "Su mensaje ha sido enviado exitosamente. Pronto nos pondremos en contacto con usted!"
        })
    else:
        return render(request, "inventarios/contacto.html")


# Funcion para crear nuevos usuarios (Exclusiva Gerente)
@login_required(login_url="inventarios/ingresar")
def signup_view(request):
    if request.method == "POST":
        # Formulario de creacion de usuario creado en operaciones/forms.py
        form = SignUpForm(request.POST)
        # Validacion
        if form.is_valid():
            # Guarda el usuario creado
            form.save()
            # Retorna a la pagina del menu del gerente
            return render(request, "inventarios/gerente.html", {
                "mensaje": "Nuevo Usuario Creado Exitosamente. Recuerde Diligenciar el Formulario del Nuevo Contratista"
            })
        # Si la validacion no pasa
        else:
            form = SignUpForm()
            return render(request, "inventarios/signup.html", {
                "form": form,
                "mensaje": "Verfique los datos ingresados e intente nuevamente!"
            })
    # Si el metodo es GET
    else:
        # Muestra el formulario de creacion de usuario por defecto de django
        form = SignUpForm()
        return render(request, "inventarios/signup.html", {
            "form": form
        })


# Funcio para ingresar usuarios y autenticar credenciales
def ingresar(request):
    # Si el usuario accede via POST
    if request.method == "POST":
        # Crea el formulario de autenticacion. Este requiere incluir el
        # parametro (data=request.POST)
        formulario = AuthenticationForm(data=request.POST)
        # Validacion
        if formulario.is_valid():
            # Permite el ingreso al usuario
            # Obtiene los datos del usuario de las variables del formulario
            usuario = formulario.get_user()
            # Ingresa en la pagina web usando la variable usuario como
            # parametro
            if usuario.cargo_empleado == "Gerente General":  # Perfil del Gerente
                login(request, usuario)
                # Como solo se redirecciona se usa redirect. Esto evita que se
                # tenga que volver a iniciar sesion en caso de recargar la
                # pagina
                return redirect("inventarios:gerente")
            # Ingresa al perfil del almacenista
            elif usuario.cargo_empleado == "Almacenista":
                login(request, usuario)
                # Como solo se redirecciona se usa redirect. Esto evita que se
                # tenga que volver a iniciar sesion en caso de recargar la
                # pagina
                return redirect("inventarios:almacenista")
            # Ingresa al perfil del director operativo
            elif usuario.cargo_empleado == "Director Operacional":
                login(request, usuario)
                # Como solo se redirecciona se usa redirect. Esto evita que se
                # tenga que volver a iniciar sesion en caso de recargar la
                # pagina
                return redirect("inventarios:directoroperativo")
                # Ingresa al perfil de cada contratista
            else:
                # Como solo se redirecciona se usa redirect. Esto evita que se
                # tenga que volver a iniciar sesion en caso de recargar la
                # pagina
                login(request, usuario)
                return redirect("inventarios:contratista")

        # Si la validacion del formulario no es correcta, se retorna a la
        # pagina de inicio de sesion
        else:
            return render(request, "inventarios/ingresar.html", {
                "formulario": formulario,
                "mensaje": "Upss. Algo salió mal. Su usuario o contraseña no son correctos.Vuelva a Intentar!",
            })

    # Si el usuario accede via GET
    else:
        # Crea y muestra el formulario de inicio de sesion
        formulario = AuthenticationForm()
        return render(request, "inventarios/ingresar.html", {
            "formulario": formulario,
        })


# Funcion para cerrar sesion
def salir_view(request):
    if request.method == "POST":
        logout(request)
        return render(request, "inventarios/index.html", {
            "mensaje": "Sesión cerrada con éxito!",
        })


@login_required(login_url=ingresar)
def gerente(request):
    usuario = CustomUser.objects.all()
    return render(request, "inventarios/gerente.html", {
        'usuario': usuario,
    })


@login_required(login_url=ingresar)
def almacenista(request):
    usuario = CustomUser.objects.all()
    return render(request, "inventarios/almacenista.html", {
        'usuario': usuario,
    })


@login_required(login_url=ingresar)
def directoroperativo(request):
    usuario = CustomUser.objects.all()
    return render(request, "inventarios/directoroperativo.html", {
        'usuario': usuario,
    })


@login_required(login_url=ingresar)
def contratista(request):
    usuario = CustomUser.objects.all()
    return render(request, "inventarios/contratista.html", {
        'usuario': usuario,
    })

inventarios/templates/inventarios/almacenista.html
{% extends "inventarios/layout.html" %}

{% block title %}
      Almacenista
{% endblock %}

{% block main %}
      <div id="b">
            {% if mensaje %}
                  <div class="message">{{ mensaje }}</div>
                  <br>
            {% endif %}
      </div>
      <section id="bflex">
            <br>
            <div class="floatLeft">
                  <div class="block">
                        <a href="{% url 'operaciones:almacenistaentrada' %}">Ingreso de Materiales a Almacen</a>
                  </div>
                  <div class="block">
                        <a href="{% url 'operaciones:almacenistanuevomaterial' %}">Nueva Materia Prima a la Base de Datos</a>
                  </div>
                  <div class="block">
                        <a href="{% url 'operaciones:salidaalmacen' %}">Salidas de Inventario</a>
                  </div>
                  <!-- <div class="block">
                        <a href="{% url 'operaciones:solautsalida' %}">Autorizaciones</a>
                  </div> -->
                  <div class="block">
                        <a href="{% url 'operaciones:almacenistareporteinventarios' %}">Reportes de Inventario</a>
                  </div>
                  <div class="block">
                        <a href="{% url 'operaciones:almacenistanuevoproveedor' %}">Ingresar Nuevo Proveedor</a>
                  </div>
                  <div class="block">
                        <a href="{% url 'operaciones:almacenistalistaproductos' %}">Editar Producto</a>
                  </div>
                  <div class="block">
                        <a href="{% url 'operaciones:almacenistalistaproveedores' %}">Editar Proveedor</a>
                  </div>
            </div>
            <div class="floatRight">
                  <svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" fill="#FF7301" class="bi bi-person-circle" viewBox="0 0 16 16">
  <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
  <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
</svg>
                  <!-- El cargo del empleado se ajusta dinamicamente de acuerdo con quien haya iniciado sesion -->
                  <h3>Perfil:&nbsp;&nbsp;<u>{{ user.cargo_empleado }}</u></h3>
                  <br>
                  <!-- Se usa para mostrar el usuario cuando ha iniciado sesion -->
                  {% if user.is_authenticated %}
                        <h3>Usuario: {{ user }}</h3>
                  {% endif %}
                  <br>
                  <div class="centering logout">
                        <!-- Formulario necesario para ejecutar la vista salir_view en inventarios/views.py -->
                        <form action="{% url 'inventarios:salir' %}" method="post">
                              {% csrf_token %}
                              <input autofocus type="submit" value="Cerrar Sesión" class="logout" title="Cerrar Sesión {{ user.cargo_empleado }}">
                        </form>
                  </div>
            </div>
            <br><br>
      </section>   
{% endblock %}

inventarios/templates/inventarios/contacto.html
{% extends "inventarios/layout.html" %}

{% block title %}
    Contáctenos
{% endblock %}

{% block main %}
    <section id="b">
        {% if mensaje %}
                  <div class="message">{{ mensaje }}</div>
                  <br>
            {% endif %}
        <h2>Contacto</h2>
        <form action="{% url 'inventarios:enviarcorreogeneral' %}" method="post" class="LoginForm">
            {% csrf_token %}
            <p>Asunto: <input autofocus type="text" name="txtAsunto" /></p>
            <p>Email de Contacto: <input type="email" name="txtEmail" /></p>
            <p>
                Mensaje:
                <textarea name="txtMensaje"></textarea>
            </p>
            <input type="submit" value="Enviar" />
        </form>
        <br>
        <p>Ciudad:Ibague-Tolima</p>
        <p>Telefono:748-92-12</p> 
        <p>Direccion: calle 11 Nª 15-50</p> 
        <p>Correo:j&jconstruyproyec@hotmail.com</p>       
    </section>   
{% endblock %}

inventarios/templates/inventarios/directoroperativo.html
{% extends "inventarios/layout.html" %}

{% block title %}
      Director Operacional
{% endblock %}

{% block main %}
      <div id="b">
            {% if mensaje %}
                  <div class="message">{{ mensaje }}</div>
                  <br>
            {% endif %}
      </div>
      <section id="bflex">
            <br>
            <div class="floatLeft">
                  <div class="block">
                        <a href="{% url 'operaciones:operativoreporteinventarios' %}">Reportes de Inventario</a>
                  </div>
                  <div class="block">
                        <a href="{% url 'operaciones:solicitudmateriales' %}">Solicitud de Materias Primas</a>
                  </div>
                  <div class="block">
                        <a href="{% url 'operaciones:operativonuevoproyecto' %}">Nuevo Proyecto</a>
                  </div>
                  <div class="block">
                        <a href="{% url 'operaciones:operativolistaproyectos' %}">Editar Proyecto</a>
                  </div>
            </div>
            <div class="floatRight">
                  <svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" fill="#FF7301" class="bi bi-person-circle" viewBox="0 0 16 16">
  <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
  <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
</svg>
                  <!-- El cargo del empleado se ajusta dinamicamente de acuerdo con quien haya iniciado sesion -->
                  <h3>Perfil:&nbsp;&nbsp;<u>{{ user.cargo_empleado }}</u></h3>
                  <br>
                  <!-- Se usa para mostrar el usuario cuando ha iniciado sesion -->
                  {% if user.is_authenticated %}
                        <h3>Usuario: {{ user }}</h3>
                  {% endif %}
                  <br>
                  <div class="centering logout">
                        <!-- Formulario necesario para ejecutar la vista salir_view en inventarios/views.py -->
                        <form action="{% url 'inventarios:salir' %}" method="post">
                              {% csrf_token %}
                              <input autofocus type="submit" value="Cerrar Sesión" class="logout" title="Cerrar Sesión {{ user.cargo_empleado }}">
                        </form>
                  </div>
            </div>
            <br><br>
      </section>   
{% endblock %}

inventarios/templates/inventarios/gerente.html
{% extends "inventarios/layout.html" %}

{% block main %}
      <div id="b">
            {% if mensaje %}
                  <div class="message">{{ mensaje }}</div>
                  <br>
            {% endif %}
      </div>
      <section id="bflex">
            <br>
            <div class="floatLeft">
                  <div class="block">
                        <a href="{% url 'operaciones:reportesinventario' %}">Reportes de Inventario</a>
                  </div>
                  <div class="block">
                        <a href="{% url 'operaciones:entradaalmacen' %}">Ingreso de Materiales a Almacen</a>
                  </div>
                  <div class="block">
                        <a href="{% url 'operaciones:nuevomaterial' %}">Nueva Materia Prima a Base de Datos</a>
                  </div>
                  <div class="block" title="Para editar datos del usuario ya registrados ingrese a admin!!!">
                        <a href="{% url 'inventarios:signup' %}"><b>Nuevo Usuario</b></a>
                  </div>
                  <div class="block">
                        <a href="{% url 'operaciones:nuevocontratista' %}"><b>Nuevo Contratista</b></a>
                  </div>
                  <div class="block">
                        <a href="{% url 'operaciones:nuevoproveedor' %}"> Nuevo Proveedor</a>
                  </div>
                  <div class="block">
                        <a href="{% url 'operaciones:nuevoproyecto' %}">Nuevo Proyecto</a>
                  </div>
                  <!-- <div class="block">
                        <a href="{% url 'operaciones:autsalidamaterial' %}">Autorizar Orden de Salida de Material</a>
                  </div> -->
                  <div class="block">
                        <a href="{% url 'operaciones:eliminarcontratista' %}">Editar o Eliminar Contratista</a>
                  </div>
                  <div class="block">
                        <a href="{% url 'operaciones:eliminarproducto' %}">Editar o Eliminar Producto</a>
                  </div>
                  <div class="block">
                        <a href="{% url 'operaciones:eliminarproveedor' %}">Editar o Eliminar Proveedor</a>
                  </div>
                  <div class="block">
                        <a href="{% url 'operaciones:eliminarproyecto' %}">Editar o Eliminar Proyecto</a>
                  </div>
            </div>
            <div class="floatRight">
                  <svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" fill="#FF7301" class="bi bi-person-circle" viewBox="0 0 16 16">
  <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
  <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
</svg>
                  <!-- El cargo del empleado se ajusta dinamicamente de acuerdo con quien haya iniciado sesion -->
                  <h3>Perfil:&nbsp;&nbsp;<u>{{ user.cargo_empleado }}</u></h3>
                  <br>
                  <!-- Se usa para mostrar el usuario cuando ha iniciado sesion -->
                  {% if user.is_authenticated %}
                        <h3>Usuario: {{ user }}</h3>
                  {% endif %}
                  <br>
                  <br>
                  <div class="centering logout">
                        <!-- Formulario necesario para ejecutar la vista salir_view en inventarios/views.py -->
                        <form action="{% url 'inventarios:salir' %}" method="post">
                              {% csrf_token %}
                              <input autofocus type="submit" value="Cerrar Sesión" class="logout" title="Cerrar Sesión {{ user.cargo_empleado }}">
                        </form>
                  </div>
            </div>
            <br><br>
      </section>   
{% endblock %}

inventarios/templates/inventarios/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> 
        {% block title %} {% endblock %}
    </title>
    <link rel="stylesheet" href="{% static 'inventarios/styles.css' %}?{% now 'U' %}">
    <link href ="https://file.myfontastic.com/KL3SN5cnuidMLxZSwWuarG/icons.css" rel = "hoja de estilo">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Sofia&effect=neon|outline|emboss|shadow-multiple">
   
</head>
<body>
    <header>
        <div class="contenedor">
            <img class="main_logo" src="{% static 'inventarios/Logo_J&J2.png' %}">
            <input type= "checkbox" id="menu-bar">
            <label class="icon-menu" for="menu-bar"></label>
            <nav class="menu">
                <a href="{% url 'inventarios:index' %}" class="href">Inicio</a>
                <a href="{% url 'inventarios:mision' %}" class="href">Mision</a>
                <a href="{% url 'inventarios:vision' %}" class="href">Vision</a>
                <a href="{% url 'inventarios:contacto' %}" class="href">Contacto</a>
                <a href="{% url 'inventarios:ingresar' %}" class="href">Ingresar</a>
            </nav>
        </div>    
    </header>
    <main>
    <section id="portada">
        <img src="{% static 'inventarios/port.jpeg' %}">
        <div class="contenedor">
            <h2 class="font-effect-shadow-multiple">LOS MEJORES TRABAJOS CON LA MEJOR CALIDAD</h2>
            <p class="font-effect-shadow-multiple">NUESTRA COMPAÑIA TRABAJA CON LOS MEJORES MATERIALES Y OFRECE 
            TRABAJOS GRANTIZADOS PARA SATISFACER A LOS CLIENTES MÁS EXIGENTES</p>
        </div>
    </section>

    <!--Espacio para inyectar el contenido unico de cada pagina -->
    <div class="main">
    {% block main %}
        
    {% endblock %}  
    </div>  
    <hr>
    <br>

    <section id="bien">

        <h3>NUESTRA MANO DE OBRA</h3>
        <div class="contenedor">
            <article>
                <img src="{% static 'inventarios/foto1.jpeg' %}">
            </article>

            <article>
                <img src="{% static 'inventarios/foto2.jpeg' %}">
            </article>

            <article>
                <img src="{% static 'inventarios/foto3.jpeg' %}">
            </article>
        </div>
    </section>
            
        </section>
        <section id="info">
            <h3>NUESTROS MATERIALES</h3>
            <div class="contenedor">
            <div class="info-m">
                <img src="{% static 'inventarios/img1.jpeg' %}">
                <h4>Varillas de hierro</h4>
            </div>   

            <div class="info-m">
                <img src="{% static 'inventarios/img2.jpeg' %}">
                <h4>Tornillos de bronce</h4>
            </div> 

            <div class="info-m">
                <img src="{% static 'inventarios/img3.jpeg' %}">
                <h4>Tornillos de acero</h4> 
            </div>  

            <div class="info-m">
                <img src="{% static 'inventarios/img4.jpeg' %}">
                <h4>Cables de aluminio</h3>
            </div>              
            </div>
        </section>
    </main>
    <footer>
        <div class="contenedor">
            <div class="copy">
            <pre class="copy">COPYRIGHT © 2021 Proyectos Y Construcciones J&J S.A.S</pre> 
                <pre>Ciudad:Ibague-Tolima</pre>
                <pre>Telefono:748-92-12</pre> 
                <pre>Direccion: calle 11 Nª 15-50</pre> 
                <pre id="correo">Correo:j&jconstruyproyec@hotmail.com</pre></div></p>
            <div class="redessociales">
                <a class="icon-facebook" href="https://www.facebook.com" target="_blank"></a>
                <a class="icon-twitter" href="http://www.twitter.com" target="_blank"></a>
                <a class="icon-youtube" href="http://www.youtube.com" target="_blank"></a>
                <a class="icon-instagram" href="http://www.instagram.com" target="_blank"></a>
                <a class="icon-whatsapp" href="http://www.whatsapp.com" target="_blank"></a>
            </div>
        </div>
    </footer>
    <script src="{% static 'inventarios/script.js' %}"></script>
</body>
</html>