Proyecto_JYJSAS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
# Importa el archivo views de inventarios para redireccionar con el
# path("", views.index, name="index") a la url http://127.0.0.1:8000
from inventarios import views


urlpatterns = [
    path('admin/', admin.site.urls),
    # Path para la aplicacion inventarios
    path('inventarios/', include('inventarios.urls')),
    # Redirecciona como pagina principal a la url http://127.0.0.1:8000/
    path("", views.index, name="index"),
    # Path para la aplicacion operaciones
    path('operaciones/', include('operaciones.urls'))
]

inventarios/urls.py
from django.urls import path
from . import views


# Namespace para evitar conflicto entre urls llamadas igual pero en diferentes
# aplicaciones
app_name = "inventarios"

urlpatterns = [
    # Camino a la pagina principal de la empresa
    path("", views.index, name="index"),
    path("mision", views.mision, name="mision"),
    path("vision", views.vision, name="vision"),
    path("contacto", views.contacto, name="contacto"),
    path("enviarcorreogeneral", views.enviarcorreogeneral,
         name="enviarcorreogeneral"),
    path("ingresar", views.ingresar, name="ingresar"),
    path("salir", views.salir_view, name="salir"),
    path("gerente", views.gerente, name="gerente"),
    path("almacenista", views.almacenista, name="almacenista"),
    path("directoroperativo", views.directoroperativo,
         name="directoroperativo"),
    path("contratista", views.contratista, name="contratista"),
    path("signup", views.signup_view, name="signup")
]

operaciones/urls.py
from django.urls import path
from . import views


# Namespace para evitar conflicto entre urls llamadas igual pero en diferentes
# aplicaciones
app_name = "operaciones"

urlpatterns = [
     ############################ Paginas gerente ##############################
     path("", views.index, name="reportesinventario"),
     path("nuevomaterial", views.nuevomaterial, name="nuevomaterial"),
     path("nuevoproveedor", views.nuevoproveedor, name="nuevoproveedor"),
     path("nuevoproyecto", views.nuevoproyecto, name="nuevoproyecto"),
     path("nuevocontratista", views.nuevocontratista, name="nuevocontratista"),
     # Pagina de entradas de almacen
     path("entradaalmacen", views.entradaalmacen, name="entradaalmacen"),
     path("autsalidamaterial", views.autsalidamaterial,
          name="autsalidamaterial"),
     path("eliminarcontratista", views.eliminarcontratista,
          name="eliminarcontratista"),
     path("eliminarproducto", views.eliminarproducto, name="eliminarproducto"),
     path("eliminarproveedor", views.eliminarproveedor,
          name="eliminarproveedor"),
     path("eliminarproyecto", views.eliminarproyecto,
          name="eliminarproyecto"),
     # Pagina borrado exclusiva de un contratista
     path("borrarcontratista<int:codigo_contratista>", views.borrarcontratista,
          name="borrarcontratista"),
     # Pagina borrado exclusiva de un producto de almacen
     path("borrarproducto<int:codigo_producto>", views.borrarproducto,
          name="borrarproducto"),
     # Pagina borrado exclusiva de un proveedor
     path("borrarproveedor<int:codigo_proveedor>", views.borrarproveedor,
          name="borrarproveedor"),
     # Pagina borrado exclusiva de un proyecto
     path("borrarproyecto<int:codigo_proyecto>", views.borrarproyecto,
          name="borrarproyecto"),
     # Pagina para editar exclusivamente a un contratista
     path("editarcontratista<int:codigo_contratista>", views.editarcontratista,
          name="editarcontratista"),
     # Pagina de edicion exclusiva de un producto
     path("editarproducto<int:codigo_producto>", views.editarproducto,
          name="editarproducto"),     
     # Pagina de edicion exclusiva de un proveedor
     path("editarproveedor<int:codigo_proveedor>",
          views.editarproveedor, name="editarproveedor"),
     # Pagina de edicion exclusiva de un proyecto
     path("editarproyecto<int:codigo_proyecto>", views.editarproyecto,
          name="editarproyecto"),
     # Ruta para redirecionar al gerente al menu de el mismo
     path("redirecciongerente", views.redirecciongerente,
          name="redirecciongerente"),  # Redirecciona al menu del gerente
     
     # ######################### Paginas almacenista ########################
     path("almacenistanuevomaterial", views.almacenistanuevomaterial,
          name="almacenistanuevomaterial"),
     # Pagina que lista todos los productos del almacen
     path("almacenistalistaproductos", views.almacenistalistaproductos,
          name="almacenistalistaproductos"),
     # Pagina para editar un producto especifico de la base de datos
     path("almacenistaeditarproducto<int:codigo_producto>", views.almacenistaeditarproducto,
          name="almacenistaeditarproducto"),
     # Pagina que lista todos los proveedores
     path("almacenistalistaproveedores", views.almacenistalistaproveedores,
          name="almacenistalistaproveedores"),
     # Pagina para editar un proveedor especifico de la base de datos
     path("almacenistaeditarproveedor<int:codigo_proveedor>",
          views.almacenistaeditarproveedor, name="almacenistaeditarproveedor"),
     path("salidaalmacen", views.salidaalmacen, name="salidaalmacen"),
     path("almacenistaentrada", views.almacenistaentrada,
          name="almacenistaentrada"),
     path("solautsalida", views.solautsalida, name="solautsalida"),
     path("almacenistareporteinventarios", views.almacenistareporteinventarios,
          name="almacenistareporteinventarios"),
     path("almacenistanuevoproveedor", views.almacenistanuevoproveedor,
          name="almacenistanuevoproveedor"),
     path("redireccionalmacenista", views.redireccionalmacenista,
          name="redireccionalmacenista"),  # Redirecciona al menu almacenista

     # ##################### Paginas director operativo #######################
     path("operativoreporteinventarios", views.operativoreporteinventarios,
          name="operativoreporteinventarios"),
     path("solicitudmateriales", views.solicitudmateriales,
          name="solicitudmateriales"),
     path("operativonuevoproyecto", views.operativonuevoproyecto,
          name="operativonuevoproyecto"),
     path("operativolistaproyectos", views.operativolistaproyectos,
          name="operativolistaproyectos"),
     path("operativoeditarproyecto<int:codigo_proyecto>",
          views.operativoeditarproyecto, name="operativoeditarproyecto"),
     path("redireccionoperativo", views.redireccionoperativo,
          name="redireccionoperativo"),  # Redirecciona al menu del operativo

     # ######################## Paginas contratistas ##########################
     path("proyectoscontratista", views.proyectoscontratista,
          name="proyectoscontratista"),
     # path("proyectoscontratista<int:pk>", views.proyectoscontratista,
     #      name="proyectoscontratista"),
     path("novedades", views.novedades, name="novedades"),
     path("enviarnovedades", views.enviarnovedades, name="enviarnovedades"),
     path("redireccioncontratista", views.redireccioncontratista,
         name="redireccioncontratista"),  # Redirecciona al menu contratistas
     
     # ###################### Paginas de Reportes #############################
     path("reportedisponibilidad", views.reportedisponibilidad,
          name="reportedisponibilidad"),
     path("reportedisponibilidadalmacenista",
          views.reportedisponibilidadalmacenista,
          name="reportedisponibilidadalmacenista"),
     path("reportedisponibilidadoperativo",
          views.reportedisponibilidadoperativo,
          name="reportedisponibilidadoperativo"),
     path("reporteporproyecto", views.reporteporproyecto,
          name="reporteporproyecto"),
     path("almacenistareporteporproyecto", views.almacenistareporteporproyecto,
          name="almacenistareporteporproyecto"),
     path("operativoreporteporproyecto", views.operativoreporteporproyecto,
          name="operativoreporteporproyecto")
]

operaciones/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
""" Como los modelos a usar estan en la carpeta de la aplicacion inventarios se
deben importar a la carpeta de la aplicacion operaciones para poder hacer uso
de ellos en los formularios que van a ir en las diferentes paginas web de
operaciones """
from . import models


# Clase para insertar los datos en el modelo Materia_prima al ingresar nuevos
# productos al almacen.
class NuevoProducto(forms.ModelForm):
    class Meta:
        # Define los campos a presetar y el modelo del que heredan.
        model = models.Materia_prima
        # Campos a mostrar
        fields = ['codigo_producto', 'nombre_producto', 'unidad_de_medida',
                  'precio_unitario', 'marca',  'Proveedores_cod_proveedor'
                  ]
        

# Clase para editar productos
class EditarProducto(forms.ModelForm):
    class Meta:
        # Modelo del que hereda
        model = models.Materia_prima
        # Campos del formulario
        fields = [
            'nombre_producto', 'unidad_de_medida',
            'precio_unitario', 'marca',  'Proveedores_cod_proveedor'
        ]


# Clase para insertar material que ya esta en base de datos en la tabla
# Materia_prima 
class Entrada_Almacen(forms.ModelForm):
    class Meta:
        # Define los campos a presetar y el modelo del que heredan.
        model = models.EntradasAlmacen
        # Campos a mostrar
        fields = ['codigo_material', 'numero_factura_compra', 'cantidad']


# Clase para registrar nuevos usuarios del gerente
class SignUpForm(UserCreationForm):
    class Meta:
        model = models.CustomUser
        fields = [
            'username', 'password1', 'password2', 'first_name',
            'last_name', 'identificacion',  'telefono_empleado', 'email',
            'cargo_empleado'
        ]
        

# Clase para insertar datos de nuevos contratistas
class NuevoContratista(forms.ModelForm):
    class Meta:
        # Define los campos a presentar y el modelo que heredan
        model = models.Contratistas
        # Campos del formulario
        fields = [
            'codigo_contratista', 'nombre_contratista', 'apellido_contratista',
            'identificacion', 'direccion_contratista', 'correo_contratista',
            'telefono_contratista', 'especialidad_contratista',
            'proyecto_asignacion'
        ]
        
        
# Clase para editar contratistas
class EditarContratista(forms.ModelForm):
    class Meta:
        # Define los campos a presentar y el modelo que heredan
        model = models.Contratistas
        # Campos del formulario
        fields = [
            "nombre_contratista", "apellido_contratista", "identificacion",
            "direccion_contratista", "correo_contratista",
            "telefono_contratista", "especialidad_contratista",
            "proyecto_asignacion"
        ]


# Clase para insertar datos de nuevos proveedores
class NuevoProveedor(forms.ModelForm):
    class Meta:
        # Define los campos a presentar y el modelo que heredan
        model = models.Proveedores
        # Campos del formulario
        fields = [
            'codigo_proveedor', 'nombre_proveedor', 'direccion_proveedor',
            'barrio_proveedor', 'ciudad_proveedor', 'telefono_proveedor',
            'website_proveedor', 'email', 'maneja_credito'
        ]


# Clase para editar proveedores
class EditarProveedor(forms.ModelForm):
    class Meta:
        # Modelo del que hereda
        model = models.Proveedores
        # Campos del formulario
        fields = [
            'nombre_proveedor', 'direccion_proveedor', 'barrio_proveedor',
            'ciudad_proveedor', 'telefono_proveedor', 'website_proveedor',
            'email', 'maneja_credito'
        ]


# Clase para insertar nuevos proyectos
class NuevoProyecto(forms.ModelForm):
    class Meta:
        # Define los campos a presentar y el modelo que heredan
        model = models.Proyectos
        # Campos del formulario
        fields = [
            'codigo_proyecto', 'nombre_proyecto', 'direccion_proyecto',
            'descripcion_proyecto', 'estado_proyecto', 'empleado_responsable'
        ]


# Clase para editar proyectos
class EditarProyecto(forms.ModelForm):
    class Meta:
        # Modelo del que hereda
        model = models.Proyectos
        fields = [
            'nombre_proyecto', 'direccion_proyecto', 'descripcion_proyecto',
            'estado_proyecto', 'empleado_responsable'
        ]

operaciones/templates/operaciones/almacenistaeditarproducto.html
{% extends "inventarios/layout.html" %}

{% block title %}
    Editar Producto Almacenista
{% endblock %}

{% block main %}
    <div id="b">
            {% if mensaje %}
                  <div class="error">{{ mensaje }}</div>
                  <br>
            {% endif %}
      </div>
    <div class="centering error">
        <h2>Página de Edición del Producto: <u>{{ producto }}</u> </h2>
    </div>
    <br>
      <section id="bflex">
            <br>
            <div class="floatLeft">
                  <table>
                    <tr>
                        <th><h4>Código</h4></th>
                        <th><h4>{{ producto.codigo_producto }}</h4></th>
                    </tr>
                    <tr>
                        <!-- En los campos input, se establecen tipos y valores similares de los de los modelos en operacions/models.py -->
                        <form href="{% url 'operaciones:almacenistaeditarproducto' producto.codigo_producto %}" method="post">
                            {% csrf_token %}
                            {{ formulario }}
                            <td><b><p>Edición</p></b></td>
                            <td>
                                <input type="submit" value="Confirmar Edición" autofocus class="edition">
                            </td>
                        </form>
                    </tr>
                </table>
            </div>
            <div class="floatRight">
                  <svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" fill="#FF7301" class="bi bi-person-circle" viewBox="0 0 16 16">
  <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
  <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
</svg>
                  <!-- El cargo del empleado se ajusta dinamicamente de acuerdo con quien haya iniciado sesion -->
                  <h3>Perfil:&nbsp;&nbsp;<u>{{ user.cargo_empleado }}</u></h3>
                  <br>
                  <!-- Se usa para mostrar el usuario cuando ha iniciado sesion -->
                  {% if user.is_authenticated %}
                        <h3>Usuario: {{ user.username }}</h3>
                  {% endif %}
                  <br>
                  <div class="centering logout">
                        <form action="{% url 'operaciones:redireccionalmacenista' %}" method="post">
                              {% csrf_token %}
                              <input autofocus type="submit" Value="Volver al Menú" class="logout" title="Volver al Menú {{ user.cargo_empleado }}">
                        </form>
                  </div>
                  <br>
                  <div class="centering logout">
                        <!-- Formulario necesario para ejecutar la vista salir_view en inventarios/views.py -->
                        <form action="{% url 'inventarios:salir' %}" method="post">
                              {% csrf_token %}
                              <input type="submit" value="Cerrar Sesión" class="logout" title="Cerrar Sesión {{ user.cargo_empleado }}">
                        </form>
                  </div>
            </div>
            <br><br>
      </section>
{% endblock %}

operaciones/templates/operaciones/almacenistalistaproductos.html
{% extends "inventarios/layout.html" %}

{% block title %}
    Selección Producto a Editar Almacenista
{% endblock %}

{% block main %}
      <div class="centering">
            <h2>Editar Productos</h2>
      </div>
      <section id="bflex">
            <br>
            <div class="floatLeftTabla">
                  <table>
                        <tr>
                              <th><h4>Código</h4></th>
                              <th><h4>Nombre</h4></th>
                              <th><h4>U. Medida</h4></th>
                              <th><h4>Marca</h4></th>
                              <th><h4>Precio</h4></th>
                              <th><h4>Proveedor</h4></th>
                              <th><h4>Editar</h4></th>
                        </tr>
                  {% for producto in listado %}
                        <tr>
                              <td><p>{{ producto.codigo_producto }}</p></td>
                              <td><p>{{ producto.nombre_producto }}</p></td>
                              <td><p>{{ producto.unidad_de_medida }}</p></td>
                              <td><p>{{ producto.marca }}</p></td>
                              <td><p>${{ producto.precio_unitario }}</p></td>
                              <td>
                                    <ul>
                                          {% for proveedor in producto.Proveedores_cod_proveedor.all %}
                                                <li>{{ proveedor }}</li>
                                          {% endfor %}
                                    </ul>
                              </td>
                              <td><a href="{% url 'operaciones:almacenistaeditarproducto' producto.codigo_producto %}">Editar Producto</a></td>
                        </tr>
                  {% endfor %}
                  </table>
            </div>
            <div class="floatRight">
                  <svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" fill="#FF7301" class="bi bi-person-circle" viewBox="0 0 16 16">
  <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
  <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
</svg>
                  <!-- El cargo del empleado se ajusta dinamicamente de acuerdo con quien haya iniciado sesion -->
                  <h3>Perfil:&nbsp;&nbsp;<u>{{ user.cargo_empleado }}</u></h3>
                  <br>
                  <!-- Se usa para mostrar el usuario cuando ha iniciado sesion -->
                  {% if user.is_authenticated %}
                        <h3>Usuario: {{ user.username }}</h3>
                  {% endif %}
                  <br>
                  <div class="centering logout">
                        <form action="{% url 'operaciones:redireccionalmacenista' %}" method="post">
                              {% csrf_token %}
                              <input autofocus type="submit" Value="Volver al Menú" class="logout" title="Volver al Menú {{ user.cargo_empleado }}">
                        </form>
                  </div>
                  <br>
                  <div class="centering logout">
                        <!-- Formulario necesario para ejecutar la vista salir_view en inventarios/views.py -->
                        <form action="{% url 'inventarios:salir' %}" method="post">
                              {% csrf_token %}
                              <input type="submit" value="Cerrar Sesión" class="logout" title="Cerrar Sesión {{ user.cargo_empleado }}">
                        </form>
                  </div>
            </div>
            <br><br>
      </section>
{% endblock %}

operaciones/templates/operaciones/editarproveedor.html
{% extends "inventarios/layout.html" %}

{% block title %}
    Editar Proveedor Gerente
{% endblock %}

{% block main %}
    <div id="b">
            {% if mensaje %}
                  <div class="error">{{ mensaje }}</div>
                  <br>
            {% endif %}
      </div>
    <div class="centering error">
        <h2>Página de Edición del Proveedor: <u>{{ proveedor }}</u> </h2>
    </div>
    <br>
      <section id="bflex">
            <br>
            <div class="floatLeft">
                  <table>
                    <tr>
                        <th><h4>Código</h4></th>
                        <th><h4>{{ proveedor.codigo_proveedor }}</h4></th>
                    </tr>
                    <tr>
                        <!-- En los campos input, se establecen tipos y valores similares de los de los modelos en operacions/models.py -->
                        <form href="{% url 'operaciones:editarproveedor' proveedor.codigo_proveedor %}"method="post">
                            {% csrf_token %}
                            {{ formulario }}
                            <td><b><p>Edición</p></b></td>
                            <!-- Para listar una casilla de muchos a muchos, es necesario un for loop.-->
                            <td>
                                <input type="submit" value="Confirmar Edición" autofocus class="edition">
                            </td>
                        </form>
                    </tr>
                </table>
            </div>
            <div class="floatRight">
                  <svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" fill="#FF7301" class="bi bi-person-circle" viewBox="0 0 16 16">
  <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
  <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
</svg>
                  <!-- El cargo del empleado se ajusta dinamicamente de acuerdo con quien haya iniciado sesion -->
                  <h3>Perfil:&nbsp;&nbsp;<u>{{ user.cargo_empleado }}</u></h3>
                  <br>
                  <!-- Se usa para mostrar el usuario cuando ha iniciado sesion -->
                  {% if user.is_authenticated %}
                        <h3>Usuario: {{ user.username }}</h3>
                  {% endif %}
                  <br>
                  <div class="centering logout">
                        <form action="{% url 'operaciones:redirecciongerente' %}" method="post">
                              {% csrf_token %}
                              <input autofocus type="submit" Value="Volver al Menú" class="logout" title="Volver al Menú {{ user.cargo_empleado }}">
                        </form>
                  </div>
                  <br>
                  <div class="centering logout">
                        <!-- Formulario necesario para ejecutar la vista salir_view en inventarios/views.py -->
                        <form action="{% url 'inventarios:salir' %}" method="post">
                              {% csrf_token %}
                              <input type="submit" value="Cerrar Sesión" class="logout" title="Cerrar Sesión {{ user.cargo_empleado }}">
                        </form>
                  </div>
            </div>
            <br><br>
      </section>
{% endblock %}

operaciones/templates/operaciones/eliminarcontratista.html
{% extends "inventarios/layout.html" %}

{% block title %}
    Eliminar Contratista Gerente
{% endblock %}

{% block main %}
      <div class="centering">
            <h2>Editar o Eliminar Contratistas</h2>
      </div>
      <section id="bflex">
            <br>
            <div class="floatLeftTabla">
                  <table>
                        <tr>
                              <th><h4>Código</h4></th>
                              <th><h4>Nombre</h4></th>
                              <th><h4>Identificación</h4></th>
                              <th><h4>Dirección</h4></th>
                              <th><h4>Teléfono</h4></th>
                              <th><h4>Correo</h4></th>
                              <th><h4>Especialidad</h4></th>
                              <th><h4>Proyectos</h4></th>
                              <th><h4>Editar</h4></th>
                              <th><h4>Eliminar</h4></th>
                        </tr>
                        {% for contratista in listado %}
                              <tr>
                                    <td><p>{{ contratista.codigo_contratista }}</p></td>
                                    <td><p>{{ contratista.nombre_contratista }} {{ contratista.apellido_contratista }}</p></td>
                                    <td><p>{{ contratista.identificacion }}</p></td>
                                    <td><p>{{ contratista.direccion_contratista }}</p></td>
                                    <td><p>{{ contratista.telefono_contratista }}</p></td>
                                    <td><p>{{ contratista.correo_contratista }}</p></td>
                                    <td><p>{{ contratista.especialidad_contratista }}</p></td>
                                    <!-- Para listar una casilla de muchos a muchos, es necesario anidar un for loop dentro de otro for loop.-->
                                    <td>
                                          <ul>
                                                {% for asignado in contratista.proyecto_asignacion.all %}
                                                      <li>{{ asignado }}</li>
                                                {% endfor %}
                                          </ul>
                                    </td>
                                    <!-- Redireccionan a la pagina exclusiva del contratista para editarlo o borrarlo-->
                                    <td><a href="{% url 'operaciones:editarcontratista' contratista.codigo_contratista %}">Editar</a></td>
                                    <td><a href="{% url 'operaciones:borrarcontratista' contratista.codigo_contratista %}">Eliminar</a></td>
                              </tr>
                        {% endfor %}
                  </table>
            </div>
            <div class="floatRight">
                  <svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" fill="#FF7301" class="bi bi-person-circle" viewBox="0 0 16 16">
  <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
  <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
</svg>
                  <!-- El cargo del empleado se ajusta dinamicamente de acuerdo con quien haya iniciado sesion -->
                  <h3>Perfil:&nbsp;&nbsp;<u>{{ user.cargo_empleado }}</u></h3>
                  <br>
                  <!-- Se usa para mostrar el usuario cuando ha iniciado sesion -->
                  {% if user.is_authenticated %}
                        <h3>Usuario: {{ user.username }}</h3>
                  {% endif %}
                  <br>
                  <div class="centering logout">
                        <form action="{% url 'operaciones:redirecciongerente' %}" method="post">
                              {% csrf_token %}
                              <input autofocus type="submit" Value="Volver al Menú" class="logout" title="Volver al Menú {{ user.cargo_empleado }}">
                        </form>
                  </div>
                  <br>
                  <div class="centering logout">
                        <!-- Formulario necesario para ejecutar la vista salir_view en inventarios/views.py -->
                        <form action="{% url 'inventarios:salir' %}" method="post">
                              {% csrf_token %}
                              <input type="submit" value="Cerrar Sesión" class="logout" title="Cerrar Sesión {{ user.cargo_empleado }}">
                        </form>
                  </div>
            </div>
            <br><br>
      </section>
{% endblock %}

operaciones/templates/operaciones/eliminarproveedor.html
{% extends "inventarios/layout.html" %}

{% block title %}
    Eliminar Proveedor Gerente
{% endblock %}

{% block main %}
      <div class="centering">
            <h2>Editar o Eliminar Proveedores</h2>
      </div>
      <section id="bflex">
            <br>
            <div class="floatLeftTabla">
                  <table>
                        <tr>
                              <th><h4>Código Proveedor</h4></th>
                              <th><h4>Nombre o Razon Social Proveedor</h4></th>
                              <th><h4>Editar</h4></th>
                              <th><h4>Eliminar</h4></th>
                        </tr>
                  {% for proveedor in listado %}
                        <tr>
                              <td><p>{{ proveedor.codigo_proveedor }}</p></td>
                              <td><p>{{ proveedor.nombre_proveedor }}</p></td>
                              <td><a href="{% url 'operaciones:editarproveedor' proveedor.codigo_proveedor %}">Editar Proveedor</a></td>
                              <td><a href="{% url 'operaciones:borrarproveedor' proveedor.codigo_proveedor %}">Eliminar Proveedor</a></td>
                        </tr>
                  {% endfor %}
                  </table>
            </div>
            <div class="floatRight">
                  <svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" fill="#FF7301" class="bi bi-person-circle" viewBox="0 0 16 16">
  <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
  <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
</svg>
                  <!-- El cargo del empleado se ajusta dinamicamente de acuerdo con quien haya iniciado sesion -->
                  <h3>Perfil:&nbsp;&nbsp;<u>{{ user.cargo_empleado }}</u></h3>
                  <br>
                  <!-- Se usa para mostrar el usuario cuando ha iniciado sesion -->
                  {% if user.is_authenticated %}
                        <h3>Usuario: {{ user.username }}</h3>
                  {% endif %}
                  <br>
                  <div class="centering logout">
                        <form action="{% url 'operaciones:redirecciongerente' %}" method="post">
                              {% csrf_token %}
                              <input autofocus type="submit" Value="Volver al Menú" class="logout" title="Volver al Menú {{ user.cargo_empleado }}">
                        </form>
                  </div>
                  <br>
                  <div class="centering logout">
                        <!-- Formulario necesario para ejecutar la vista salir_view en inventarios/views.py -->
                        <form action="{% url 'inventarios:salir' %}" method="post">
                              {% csrf_token %}
                              <input type="submit" value="Cerrar Sesión" class="logout" title="Cerrar Sesión {{ user.cargo_empleado }}">
                        </form>
                  </div>
            </div>
            <br><br>
      </section>
{% endblock %}